---
- hosts: monitoring_host
  tasks:
    - name: Install Prometheus
      apt:
        name: prometheus
        state: present
        update_cache: yes

    - name: Configure Prometheus to scrape metrics
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          scrape_configs:
            - job_name: "exporter"
              static_configs:
                - targets: ["<APPLICATION_HOST_IP>:8000"]

    - name: Restart Prometheus to apply changes
      service:
        name: prometheus
        state: restarted
